// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package echo

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *Req) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Req[number], err)
}

func (x *Req) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Mes, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Resp) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Resp[number], err)
}

func (x *Resp) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.Resp, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *Req) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *Req) fastWriteField1(buf []byte) (offset int) {
	if x.Mes == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetMes())
	return offset
}

func (x *Resp) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *Resp) fastWriteField1(buf []byte) (offset int) {
	if x.Resp == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetResp())
	return offset
}

func (x *Req) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *Req) sizeField1() (n int) {
	if x.Mes == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetMes())
	return n
}

func (x *Resp) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *Resp) sizeField1() (n int) {
	if x.Resp == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetResp())
	return n
}

var fieldIDToName_Req = map[int32]string{
	1: "Mes",
}

var fieldIDToName_Resp = map[int32]string{
	1: "Resp",
}
